// import Table from '../components/layout'
import Head from 'next/head'
import Table from './table'
import Layout from 'src/components/layout'
// export default function Home() {
 
//   return (
    
//     <div className='w-4/5 m-auto'>
//       <h2 class="text-4xl font-bold mb-6 mt-6">Product Collection - table</h2>
//       <Table/>
//     </div>
//   )
// }


// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
   <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous"></link>

       </Head>
       <div className='w-4/5 m-auto'>
      <Table/>
    </div>
    </>
  )
  }

